<?php

/**
 * BaseMiembroCelula
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $celula_id
 * @property integer $discipulo_id
 * @property sfGuardUser $Discipulo
 * @property Celula $Celula
 * 
 * @method integer       getCelulaId()     Returns the current record's "celula_id" value
 * @method integer       getDiscipuloId()  Returns the current record's "discipulo_id" value
 * @method sfGuardUser   getDiscipulo()    Returns the current record's "Discipulo" value
 * @method Celula        getCelula()       Returns the current record's "Celula" value
 * @method MiembroCelula setCelulaId()     Sets the current record's "celula_id" value
 * @method MiembroCelula setDiscipuloId()  Sets the current record's "discipulo_id" value
 * @method MiembroCelula setDiscipulo()    Sets the current record's "Discipulo" value
 * @method MiembroCelula setCelula()       Sets the current record's "Celula" value
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMiembroCelula extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('miembro_celula');
        $this->hasColumn('celula_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('discipulo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));


        $this->index('MiembroDeCelula', array(
             'fields' => 
             array(
              0 => 'celula_id',
              1 => 'discipulo_id',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Discipulo', array(
             'local' => 'discipulo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Celula', array(
             'local' => 'celula_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));
    }
}