<?php

/**
 * BaseEvento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titulo
 * @property timestamp $fecha_hora
 * @property clob $lugar
 * @property clob $descripcion
 * @property integer $discipulo_id
 * @property sfGuardUser $Discipulo
 * 
 * @method string      getTitulo()       Returns the current record's "titulo" value
 * @method timestamp   getFechaHora()    Returns the current record's "fecha_hora" value
 * @method clob        getLugar()        Returns the current record's "lugar" value
 * @method clob        getDescripcion()  Returns the current record's "descripcion" value
 * @method integer     getDiscipuloId()  Returns the current record's "discipulo_id" value
 * @method sfGuardUser getDiscipulo()    Returns the current record's "Discipulo" value
 * @method Evento      setTitulo()       Sets the current record's "titulo" value
 * @method Evento      setFechaHora()    Sets the current record's "fecha_hora" value
 * @method Evento      setLugar()        Sets the current record's "lugar" value
 * @method Evento      setDescripcion()  Sets the current record's "descripcion" value
 * @method Evento      setDiscipuloId()  Sets the current record's "discipulo_id" value
 * @method Evento      setDiscipulo()    Sets the current record's "Discipulo" value
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEvento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('evento');
        $this->hasColumn('titulo', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '',
             ));
        $this->hasColumn('fecha_hora', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('lugar', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('descripcion', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('discipulo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Discipulo', array(
             'local' => 'discipulo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}