<?php

/**
 * BaseSeguimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $descripcion
 * @property date $fecha
 * @property integer $asignacion_id
 * @property integer $actividad_seguimiento_id
 * @property Asignacion $Asignacion
 * @property ActividadSeguimiento $ActividadSeguimiento
 * 
 * @method clob                 getDescripcion()              Returns the current record's "descripcion" value
 * @method date                 getFecha()                    Returns the current record's "fecha" value
 * @method integer              getAsignacionId()             Returns the current record's "asignacion_id" value
 * @method integer              getActividadSeguimientoId()   Returns the current record's "actividad_seguimiento_id" value
 * @method Asignacion           getAsignacion()               Returns the current record's "Asignacion" value
 * @method ActividadSeguimiento getActividadSeguimiento()     Returns the current record's "ActividadSeguimiento" value
 * @method Seguimiento          setDescripcion()              Sets the current record's "descripcion" value
 * @method Seguimiento          setFecha()                    Sets the current record's "fecha" value
 * @method Seguimiento          setAsignacionId()             Sets the current record's "asignacion_id" value
 * @method Seguimiento          setActividadSeguimientoId()   Sets the current record's "actividad_seguimiento_id" value
 * @method Seguimiento          setAsignacion()               Sets the current record's "Asignacion" value
 * @method Seguimiento          setActividadSeguimiento()     Sets the current record's "ActividadSeguimiento" value
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSeguimiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('seguimiento');
        $this->hasColumn('descripcion', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('asignacion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('actividad_seguimiento_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Asignacion', array(
             'local' => 'asignacion_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ActividadSeguimiento', array(
             'local' => 'actividad_seguimiento_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}