<?php

/**
 * BaseAsignacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $fecha
 * @property integer $discipulo_lider_id
 * @property integer $discipulo_nuevo_id
 * @property sfGuardUser $DiscipuloNuevo
 * @property Seguimiento $Seguimiento
 * @property Doctrine_Collection $Asignacion
 * 
 * @method date                getFecha()              Returns the current record's "fecha" value
 * @method integer             getDiscipuloLiderId()   Returns the current record's "discipulo_lider_id" value
 * @method integer             getDiscipuloNuevoId()   Returns the current record's "discipulo_nuevo_id" value
 * @method sfGuardUser         getDiscipuloNuevo()     Returns the current record's "DiscipuloNuevo" value
 * @method Seguimiento         getSeguimiento()        Returns the current record's "Seguimiento" value
 * @method Doctrine_Collection getAsignacion()         Returns the current record's "Asignacion" collection
 * @method Asignacion          setFecha()              Sets the current record's "fecha" value
 * @method Asignacion          setDiscipuloLiderId()   Sets the current record's "discipulo_lider_id" value
 * @method Asignacion          setDiscipuloNuevoId()   Sets the current record's "discipulo_nuevo_id" value
 * @method Asignacion          setDiscipuloNuevo()     Sets the current record's "DiscipuloNuevo" value
 * @method Asignacion          setSeguimiento()        Sets the current record's "Seguimiento" value
 * @method Asignacion          setAsignacion()         Sets the current record's "Asignacion" collection
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAsignacion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asignacion');
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('discipulo_lider_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('discipulo_nuevo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as DiscipuloNuevo', array(
             'local' => 'discipulo_nuevo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Seguimiento', array(
             'local' => 'id',
             'foreign' => 'asignacion_id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('sfGuardUser as Asignacion', array(
             'local' => 'discipulo_lider_id',
             'foreign' => 'id'));
    }
}