<?php

/**
 * BaseCelula
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $fecha
 * @property string $dias_celula
 * @property time $horario_celula
 * @property integer $discipulo_lider_id
 * @property sfGuardUser $Lider
 * 
 * @method date        getFecha()              Returns the current record's "fecha" value
 * @method string      getDiasCelula()         Returns the current record's "dias_celula" value
 * @method time        getHorarioCelula()      Returns the current record's "horario_celula" value
 * @method integer     getDiscipuloLiderId()   Returns the current record's "discipulo_lider_id" value
 * @method sfGuardUser getLider()              Returns the current record's "Lider" value
 * @method Celula      setFecha()              Sets the current record's "fecha" value
 * @method Celula      setDiasCelula()         Sets the current record's "dias_celula" value
 * @method Celula      setHorarioCelula()      Sets the current record's "horario_celula" value
 * @method Celula      setDiscipuloLiderId()   Sets the current record's "discipulo_lider_id" value
 * @method Celula      setLider()              Sets the current record's "Lider" value
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCelula extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('celula');
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('dias_celula', 'string', 45, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 45,
             ));
        $this->hasColumn('horario_celula', 'time', 25, array(
             'type' => 'time',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('discipulo_lider_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Lider', array(
             'local' => 'discipulo_lider_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}