<?php

/**
 * BaseAsistencia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $reunion_id
 * @property integer $miembro_celula_id
 * @property Reunion $Reunion
 * @property MiembroCelula $Miembro
 * 
 * @method integer       getReunionId()         Returns the current record's "reunion_id" value
 * @method integer       getMiembroCelulaId()   Returns the current record's "miembro_celula_id" value
 * @method Reunion       getReunion()           Returns the current record's "Reunion" value
 * @method MiembroCelula getMiembro()           Returns the current record's "Miembro" value
 * @method Asistencia    setReunionId()         Sets the current record's "reunion_id" value
 * @method Asistencia    setMiembroCelulaId()   Sets the current record's "miembro_celula_id" value
 * @method Asistencia    setReunion()           Sets the current record's "Reunion" value
 * @method Asistencia    setMiembro()           Sets the current record's "Miembro" value
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAsistencia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asistencia');
        $this->hasColumn('reunion_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('miembro_celula_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Reunion', array(
             'local' => 'reunion_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('MiembroCelula as Miembro', array(
             'local' => 'miembro_celula_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));
    }
}