<?php

/**
 * BaseFicha
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property clob $descripcion
 * @property date $fecha
 * @property integer $tipo_indicador_id
 * @property integer $discipulo_id
 * @property sfGuardUser $Discipulo
 * @property TipoIndicador $TipoIndicador
 * 
 * @method clob          getDescripcion()       Returns the current record's "descripcion" value
 * @method date          getFecha()             Returns the current record's "fecha" value
 * @method integer       getTipoIndicadorId()   Returns the current record's "tipo_indicador_id" value
 * @method integer       getDiscipuloId()       Returns the current record's "discipulo_id" value
 * @method sfGuardUser   getDiscipulo()         Returns the current record's "Discipulo" value
 * @method TipoIndicador getTipoIndicador()     Returns the current record's "TipoIndicador" value
 * @method Ficha         setDescripcion()       Sets the current record's "descripcion" value
 * @method Ficha         setFecha()             Sets the current record's "fecha" value
 * @method Ficha         setTipoIndicadorId()   Sets the current record's "tipo_indicador_id" value
 * @method Ficha         setDiscipuloId()       Sets the current record's "discipulo_id" value
 * @method Ficha         setDiscipulo()         Sets the current record's "Discipulo" value
 * @method Ficha         setTipoIndicador()     Sets the current record's "TipoIndicador" value
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseFicha extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ficha');
        $this->hasColumn('descripcion', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'length' => 25,
             ));
        $this->hasColumn('tipo_indicador_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('discipulo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Discipulo', array(
             'local' => 'discipulo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('TipoIndicador', array(
             'local' => 'tipo_indicador_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}