<?php

/**
 * BaseNivelEscuela
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property clob $descripcion
 * @property Doctrine_Collection $Nivel
 * 
 * @method string              getNombre()      Returns the current record's "nombre" value
 * @method clob                getDescripcion() Returns the current record's "descripcion" value
 * @method Doctrine_Collection getNivel()       Returns the current record's "Nivel" collection
 * @method NivelEscuela        setNombre()      Sets the current record's "nombre" value
 * @method NivelEscuela        setDescripcion() Sets the current record's "descripcion" value
 * @method NivelEscuela        setNivel()       Sets the current record's "Nivel" collection
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseNivelEscuela extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('nivel_escuela');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('descripcion', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Escuela as Nivel', array(
             'local' => 'id',
             'foreign' => 'nivel_id'));
    }
}