<?php

/**
 * BaseActividadSeguimiento
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $nombre
 * @property clob $descripcion
 * @property Doctrine_Collection $Actividad
 * 
 * @method string               getNombre()      Returns the current record's "nombre" value
 * @method clob                 getDescripcion() Returns the current record's "descripcion" value
 * @method Doctrine_Collection  getActividad()   Returns the current record's "Actividad" collection
 * @method ActividadSeguimiento setNombre()      Sets the current record's "nombre" value
 * @method ActividadSeguimiento setDescripcion() Sets the current record's "descripcion" value
 * @method ActividadSeguimiento setActividad()   Sets the current record's "Actividad" collection
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseActividadSeguimiento extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('actividad_seguimiento');
        $this->hasColumn('nombre', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('descripcion', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Seguimiento as Actividad', array(
             'local' => 'id',
             'foreign' => 'actividad_seguimiento_id'));
    }
}