<?php

/**
 * BaseMeta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $titulo
 * @property timestamp $fecha_cumplir
 * @property integer $estado
 * @property clob $descripcion
 * @property integer $discipulo_id
 * @property sfGuardUser $Discipulo
 * 
 * @method string      getTitulo()        Returns the current record's "titulo" value
 * @method timestamp   getFechaCumplir()  Returns the current record's "fecha_cumplir" value
 * @method integer     getEstado()        Returns the current record's "estado" value
 * @method clob        getDescripcion()   Returns the current record's "descripcion" value
 * @method integer     getDiscipuloId()   Returns the current record's "discipulo_id" value
 * @method sfGuardUser getDiscipulo()     Returns the current record's "Discipulo" value
 * @method Meta        setTitulo()        Sets the current record's "titulo" value
 * @method Meta        setFechaCumplir()  Sets the current record's "fecha_cumplir" value
 * @method Meta        setEstado()        Sets the current record's "estado" value
 * @method Meta        setDescripcion()   Sets the current record's "descripcion" value
 * @method Meta        setDiscipuloId()   Sets the current record's "discipulo_id" value
 * @method Meta        setDiscipulo()     Sets the current record's "Discipulo" value
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMeta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('meta');
        $this->hasColumn('titulo', 'string', 200, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 200,
             ));
        $this->hasColumn('fecha_cumplir', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('estado', 'integer', 1, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 1,
             ));
        $this->hasColumn('descripcion', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('discipulo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Discipulo', array(
             'local' => 'discipulo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}