<?php

/**
 * BaseTipoIndicador
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $indicador
 * @property integer $tipo_discipulo
 * @property Doctrine_Collection $Indicador
 * 
 * @method string              getIndicador()      Returns the current record's "indicador" value
 * @method integer             getTipoDiscipulo()  Returns the current record's "tipo_discipulo" value
 * @method Doctrine_Collection getIndicador()      Returns the current record's "Indicador" collection
 * @method TipoIndicador       setIndicador()      Sets the current record's "indicador" value
 * @method TipoIndicador       setTipoDiscipulo()  Sets the current record's "tipo_discipulo" value
 * @method TipoIndicador       setIndicador()      Sets the current record's "Indicador" collection
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTipoIndicador extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_indicador');
        $this->hasColumn('indicador', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('tipo_discipulo', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Ficha as Indicador', array(
             'local' => 'id',
             'foreign' => 'tipo_indicador_id'));
    }
}