<?php

/**
 * BaseEscuela
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $fecha_ingreso
 * @property integer $discipulo_id
 * @property integer $nivel_id
 * @property sfGuardUser $Discipulo
 * @property NivelEscuela $Nivel
 * 
 * @method timestamp    getFechaIngreso()  Returns the current record's "fecha_ingreso" value
 * @method integer      getDiscipuloId()   Returns the current record's "discipulo_id" value
 * @method integer      getNivelId()       Returns the current record's "nivel_id" value
 * @method sfGuardUser  getDiscipulo()     Returns the current record's "Discipulo" value
 * @method NivelEscuela getNivel()         Returns the current record's "Nivel" value
 * @method Escuela      setFechaIngreso()  Sets the current record's "fecha_ingreso" value
 * @method Escuela      setDiscipuloId()   Sets the current record's "discipulo_id" value
 * @method Escuela      setNivelId()       Sets the current record's "nivel_id" value
 * @method Escuela      setDiscipulo()     Sets the current record's "Discipulo" value
 * @method Escuela      setNivel()         Sets the current record's "Nivel" value
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEscuela extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('escuela');
        $this->hasColumn('fecha_ingreso', 'timestamp', 25, array(
             'type' => 'timestamp',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('discipulo_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('nivel_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as Discipulo', array(
             'local' => 'discipulo_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('NivelEscuela as Nivel', array(
             'local' => 'nivel_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}