<?php

/**
 * BaseReunion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property date $fecha
 * @property clob $palabra
 * @property clob $observaciones
 * @property integer $celula_id
 * @property Celula $Celula
 * @property Asistencia $Asistencia
 * 
 * @method date       getFecha()         Returns the current record's "fecha" value
 * @method clob       getPalabra()       Returns the current record's "palabra" value
 * @method clob       getObservaciones() Returns the current record's "observaciones" value
 * @method integer    getCelulaId()      Returns the current record's "celula_id" value
 * @method Celula     getCelula()        Returns the current record's "Celula" value
 * @method Asistencia getAsistencia()    Returns the current record's "Asistencia" value
 * @method Reunion    setFecha()         Sets the current record's "fecha" value
 * @method Reunion    setPalabra()       Sets the current record's "palabra" value
 * @method Reunion    setObservaciones() Sets the current record's "observaciones" value
 * @method Reunion    setCelulaId()      Sets the current record's "celula_id" value
 * @method Reunion    setCelula()        Sets the current record's "Celula" value
 * @method Reunion    setAsistencia()    Sets the current record's "Asistencia" value
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseReunion extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('reunion');
        $this->hasColumn('fecha', 'date', 25, array(
             'type' => 'date',
             'notnull' => true,
             'length' => 25,
             ));
        $this->hasColumn('palabra', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('observaciones', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('celula_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Celula', array(
             'local' => 'celula_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Asistencia', array(
             'local' => 'id',
             'foreign' => 'reunion_id',
             'onDelete' => 'RESTRICT'));
    }
}