<?php

/**
 * ActividadSeguimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ActividadSeguimientoTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ActividadSeguimientoTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('ActividadSeguimiento');
    }

    /**
     * Obtiene la activiadad basado en el nombre porporcionado
     * @param String $nombre_actividad El nombre para consultar
     * @return ActiviadadSeguimiento Actividad encontrada 
     */
    public function getActividadPorNombre($nombre_actividad) {
        $q = $this->createQuery('as')->where('as.nombre = ?', $nombre_actividad);
        return $q->fetchOne();
    }

}