<?php

/**
 * Asignacion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Asignacion extends BaseAsignacion {
    
    /**
     * Obtiene el nombre del nuevo discipulo para asignar
     * @return String Nombre del nuevo discipulo 
     */
    public function __toString() {
        $discipulo = $this->getDiscipuloNuevo();
        return $discipulo->getFirstName() . " " . $discipulo->getLastName();
    }

    /**
     * Asigna un discipulo nuevo a un lider
     * @param type $id_lider Identificador del lider 
     * @param type $id_nuevo Identificador del nuevo discipulo
     * @return String mensaje de confirmación OK o error 
     */
    public function asignarNuevos($id_lider, $id_nuevo) {
        $this->setDiscipuloLiderId($id_lider);
        $this->setFecha(date('Y-m-d'));
        $this->setDiscipuloNuevoId($id_nuevo);
        $this->save();
        return 'ok';
    }

}