<?php

/**
 * EscuelaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EscuelaTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object EscuelaTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Escuela');
    }

    /**
     * Obtiene la lista de niveles de un discipulo consultado, esta lista esta
     * ordenada desde el nivel mas alto.
     * @param Integer $id_disipulo El id del discipulo a consultar
     * @return  List<Escuela>
     */
    public function getNivelesElv($id_disipulo) {
        $q = $this->createQuery('elv')->where('elv.discipulo_id = ?', $id_disipulo)->orderBy('elv.id ASC');
        return $q->execute();
    }

}