<?php

/**
 * FichaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FichaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FichaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ficha');
    }
}