<?php

/**
 * MetaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MetaTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object MetaTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Meta');
    }

    /**
     * Obtiene la lista de Metas sin los registros en estado completado
     * @return Lista lista de metas
     */
    public function listaSinCompletados($discipulo_id) {
        $q = $this->createQuery('m')->where('m.estado <> ?', 2)->andWhere('m.discipulo_id = ?', $discipulo_id);
        return $q->execute();
    }

}