<?php

/**
 * MiembroCelula
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MiembroCelula extends BaseMiembroCelula {

    public function __toString() {
        return ucwords(strtolower($this->getDiscipulo()->getFirstName() . " " . $this->getDiscipulo()->getLastName()));
    }

    /**
     * Registra al lider de céula como un miembro más de la célula
     * @param Integer $celula_id El ID de la célula que ha creado
     * @param Integer $lider_id El ID del lider que tambien sera miembro
     * @return String Mensaje de resultado
     */
    public function asignarLiderAsMiembro($celula_id, $lider_id) {
        $this->setCelulaId($celula_id);
        $this->setDiscipuloId($lider_id);
        $this->save();
        return 'ok';
    }

    public function getAsistenciasReales() {
        $q = Doctrine_Core::getTable('Asistencia')->createQuery('a')
                ->where('a.miembro_celula_id = ?', $this->getDiscipuloId());
        return $q->count();
    }

    public function getCelulasTodas() {
        $q = Doctrine_Core::getTable('Celula')->createQuery('c')
                ->select('c.*')
                ->distinct()
                ->innerJoin('c.MiembroCelula m')
                ->where('m.discipulo_id = ?', $this->getDiscipuloId());
        return $q->execute();
    }
    
    public function getReunionesTodas(){
        $seguimiento = Doctrine_Core::getTable('Seguimiento')->createQuery('s')
//                ->select('s*')
//                ->distinct()
                ->innerJoin('s.Asignacion a')
                ->innerJoin('a.DiscipuloNuevo d')
                ->where('s.actividad_seguimiento_id = 5 AND d.id = ?', $this->getDiscipuloId())
                ->limit(1)
                ->execute();
        $seguimiento[0]->getFecha();
        $reuniones = 0;
        $celulas = $this->getCelulasTodas();
        foreach ($celulas as $key => $celula) {
            $reuniones += $celula->getNumeroReuniones($seguimiento[0]->getFecha());
        }
        return $reuniones;
    }
    
    public function getPorcentajeAsistencia() {
        return number_format(($this->getAsistenciasReales() / $this->getReunionesTodas()) * 100, 2);
    }

}
