<?php

/**
 * MiembroCelulaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MiembroCelulaTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object MiembroCelulaTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('MiembroCelula');
    }

    /**
     * Obtiene la lista de miembros de celula dado el id del lider, la lista
     * solo muestra todos los miembros de la célula del lider
     * @param integer $id_lider el Identificacor del lider
     * @return MiembroCelula Lista de miembros encontrados 
     */
    public function getMiembrosPorLider($id_lider) {
        $q = new Doctrine_RawSql();
        $q->select('mc.*');
        $q->from('miembro_celula mc inner join celula c on c.id = mc.celula_id inner join sf_guard_user d on mc.discipulo_id = d.id');
        $q->where('c.discipulo_lider_id = ?', $id_lider);
//        $q->andWhere('c.discipulo_lider_id NOT IN (SELECT c.discipulo_lider_id FROM celula AS c)');
        $q->addComponent('mc', 'MiembroCelula mc');
        return $q->execute();
    }
    /**
     * Obtiene la lista de miembros de celula dado el id del lider, la lista
     * solo muestra los miembros que pueden habrir célula
     * @param integer $id_lider el Identificacor del lider
     * @return MiembroCelula Lista de miembros encontrados 
     */
    public function getMiembrosLideresPorLider($id_lider) {
        $q = new Doctrine_RawSql();
        $q->select('d.*');
        $q->from('miembro_celula mc inner join celula c on c.id = mc.celula_id inner join sf_guard_user d on mc.discipulo_id = d.id');
        $q->where('c.discipulo_lider_id = ?', $id_lider);
//        $q->andWhere('d.tipo_discipulo > ?', 2);
        $q->addComponent('d', 'Discipulo d');
        return $q->execute();
    }
    
}