<?php

/**
 * MiembroCelula
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class MiembroCelula extends BaseMiembroCelula {

    public function __toString() {
        return $this->getDiscipulo()->getFirstName() . " " . $this->getDiscipulo()->getLastName();
    }

    /**
     * Registra al lider de céula como un miembro más de la célula
     * @param Integer $celula_id El ID de la célula que ha creado
     * @param Integer $lider_id El ID del lider que tambien sera miembro
     * @return String Mensaje de resultado
     */
    public function asignarLiderAsMiembro($celula_id, $lider_id) {
        $this->setCelulaId($celula_id);
        $this->setDiscipuloId($lider_id);
        $this->save();
        return 'ok';
    }

}