<?php

/**
 * NivelEscuela
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class NivelEscuela extends BaseNivelEscuela {

    public function __toString() {
        return $this->getNombre();
    }

}