<?php

/**
 * NivelEscuelaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class NivelEscuelaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object NivelEscuelaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('NivelEscuela');
    }
}