<?php

/**
 * ReunionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReunionTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ReunionTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Reunion');
    }

    /**
     * Obtiene el historial de asistencias, es decir, se obtienen las fechas en
     * las que se han dictado las células
     * @param type $celula_id La célula de la cual se quiere obtener el historial
     * @return type Fechas de reuniones
     */
    public function getHistorial($celula_id) {
        $q = $this->createQuery('r')
                ->select('r.fecha')
                ->where('r.celula_id = ?', $celula_id)
                ->orderBy('r.fecha ASC')
                ->distinct();
        return $q->execute();
    }

}