<?php

/**
 * SeguimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeguimientoTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object SeguimientoTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Seguimiento');
    }

    /**
     * Obitene la lista de asignados a un lider segun el la actividad en la que se encuentran
     * @param Integer $id_lider
     * @param String $nombre_seguimiento
     * @return Asignacion La lista de asignados encontrados 
     */
    public function getSeguimientosPorActividad($id_lider, $nombre_seguimiento) {
        $q = Doctrine_Query::create()->from('Asignacion a')
                ->innerJoin('a.Seguimiento s')
                ->innerJoin('s.ActividadSeguimiento at')
                ->where('a.discipulo_lider_id = ? AND at.nombre = ?', array($id_lider, $nombre_seguimiento));
        return $q->execute();
    }

    public function getYearsMonths() {
        $q = $this->createQuery('s')
                ->select('DISTINCT year(s.fecha) year, monthname(s.fecha) month')
                ->orderBy('s.fecha')
                ->setHydrationMode(Doctrine::HYDRATE_ARRAY);
        $result = $q->execute();
        return $result;
    }

    public function filtrarGenero($genero, $year, $month) {
        $q = $this->createQuery('s')
                ->select('DISTINCT year(s.fecha) year, monthname(s.fecha) month')
                ->leftJoin('s.Asignacion a')
                ->leftJoin('a.DiscipuloNuevo d')
                ->where('d.genero = ?', $genero)
                ->andWhere('year(s.fecha) = ? AND monthname(s.fecha) = ?', array($year, $month))
                ->orderBy('s.fecha')
                ->setHydrationMode(Doctrine::HYDRATE_ARRAY);
        $result = $q->execute();
        return $result;
    }

    public function countActividadesFecha($month, $year) {
        $q = $this->createQuery('s')
                ->innerJoin('s.ActividadSeguimiento a')
                ->select('a.nombre, s.actividad_seguimiento_id, count(s.actividad_seguimiento_id) as numero')
                ->where('monthname(s.fecha) = ?', $month)
                ->andWhere('year(s.fecha) = ?', $year)
                ->andWhere('s.actividad_seguimiento_id >= ?', 4)
                ->groupBy('s.actividad_seguimiento_id')
                ->orderBy('s.actividad_seguimiento_id')
                ->setHydrationMode(Doctrine::HYDRATE_ARRAY);
        $result = $q->execute();
        return $result;
    }

}
