<?php

/**
 * SeguimientoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SeguimientoTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object SeguimientoTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Seguimiento');
    }

    /**
     * Obitene la lista de asignados a un lider segun el la actividad en la que se encuentran
     * @param Integer $id_lider
     * @param String $nombre_seguimiento
     * @return Asignacion La lista de asignados encontrados 
     */
    public function getSeguimientosPorActividad($id_lider, $nombre_seguimiento) {
        $q = Doctrine_Query::create()->from('Asignacion a')
                ->innerJoin('a.Seguimiento s')
                ->innerJoin('s.ActividadSeguimiento at')
                ->where('a.discipulo_lider_id = ? AND at.nombre = ?', array($id_lider, $nombre_seguimiento));
        return $q->execute();
    }

}