<?php

/**
 * TipoMensajeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoMensajeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoMensajeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoMensaje');
    }
}