<?php

/**
 * TipoIndicadorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TipoIndicadorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TipoIndicadorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TipoIndicador');
    }
}