monitor:
  url:   /monitor/:id_discipulo
  param: { module: monitor, action: index }
discipulos:
  class: sfDoctrineRouteCollection
  options:
    model:                sfGuardUser
    module:               disipulos
    prefix_path:          /discipulos
    column:               id
    with_wildcard_routes: true
eventos:
  class: sfDoctrineRouteCollection
  options:
    model:                Evento
    module:               eventos
    prefix_path:          /eventos
    column:               id
    with_wildcard_routes: true
seguimiento:
  class: sfDoctrineRouteCollection
  options:
    model:                Segumineto
    module:               seguimiento
    prefix_path:          /seguimiento
    column:               id
    with_wildcard_routes: true
celulas:
  class: sfDoctrineRouteCollection
  options:
    model:                Celula
    module:               celulas
    prefix_path:          /celulas
    column:               id
    with_wildcard_routes: true
reuniones:
  class: sfDoctrineRouteCollection
  options:
    model:                Reunion
    module:               reuniones
    prefix_path:          /reuniones
    column:               id
    with_wildcard_routes: true
seguidores:
  class: sfDoctrineRouteCollection
  options:
    model:                MiembroCelula
    module:               seguidores
    prefix_path:          /seguidores
    column:               id
    with_wildcard_routes: true
asignacion:
  class: sfDoctrineRouteCollection
  options:
    model:                Discipulo
    module:               asignacion
    prefix_path:          /asignacion
    column:               id
    with_wildcard_routes: true
asignar_nuevos:
  url: /asignacion/:cadena_ids
  param: { module: asignacion, action: asignarNuevos, sf_format: html }
  requirements:
    sf_format: (?:html|js)
escuela:
  class: sfDoctrineRouteCollection
  options:
    model:                Escuela
    module:               escuela
    prefix_path:          /escuela
    column:               id
    with_wildcard_routes: true
meta:
  class: sfDoctrineRouteCollection
  options:
    model:                Meta
    module:               metas
    prefix_path:          /metas
    column:               id
    with_wildcard_routes: true
completar_meta:
  url: /meta/completar/:id/:modulo
  param: { module: metas, action: completar, sf_format: html }
  requirements:
    sf_format: (?:html|js)
cambiar_estado_discipulo:
  url: /discipulo/cambiar-estado/:id
  param: { module: disipulos, action: cambiarEstado, sf_format: html }
  requirements:
    sf_format: (?:html|js)
eliminar_discipulo:
  url: /discipulo/eliminar/:id
  param: { module: disipulos, action: borrado, sf_format: html }
  requirements:
    sf_format: (?:html|js)
cumpleaneros:
  url: /discipulo/cumpleaneros
  param: { module: disipulos, action: cumpleaneros, sf_format: html }
  requirements:
    sf_format: (?:html|js)
# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: desktop, action: index }

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

sf_guard_register:
  url:   /registar_usuario
  param: { module: sfGuardRegister, action: index }

#sf_guard_user_ajax:
#  url:   /usuarios
#  param: { module: sfGuardUser, action: index }

# generic rules
# please, remove them by adding more specific rules
#default_index:
#  url:   /:module
#  param: { action: index }
#
#default:
#  url:   /:module/:action/*
