<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser {

    /**
     * Metodo que permite imprimir el objeto
     * @return String Nombre y apellidos del discipulo
     */
    public function __toString() {
        return $this->getFirstName() . " " . $this->getLastName();
    }

    /**
     * Calcular la edad del Discipulo
     * @return Integer Edad del discipulo
     */
    public function getEdad() {
        list($anio, $mes, $dia) = explode("-", $this->getFechaNac());
        $anio_dif = date("Y") - $anio;
        $mes_dif = date("m") - $mes;
        $dia_dif = date("d") - $dia;
        if ($dia_dif < 0 || $mes_dif < 0) {
            $anio_dif--;
        }
        return $anio_dif;
    }

    /**
     * Devuelve el nombre del ícono adecuado para mostrar activo o inactivo
     * @return string 
     */
    public function getActivo() {
        $icono = "green_alert.png";
        if ($this->getIsActive() != 1) {
            $icono = "red_alert.png";
        }
        return $icono;
    }

    /**
     * Cambia el estado del campo IS_ACTIVE del discipulo
     */
    public function cambiarEstado() {
        $mensaje = "";
        if ($this->getIsActive() == 1) {
            $this->setIsActive(false);
            $mensaje = "DESACTIVADO";
        } else {
            $this->setIsActive(true);
            $mensaje = "ACTIVADO";
        }
        $this->save();
        return $mensaje;
    }

    /**
     * Obtiene el nombre de la foto del usuario, en el caso de que no se haya 
     * definido ninguno, se retorna una avatar cualquiera.
     * @return String Nombre de la imagen
     */
    public function getFoto() {
        $foto = $this->getFotografia();
        if($foto == ""){
            if($this->getGenero() == 1) {
                return "avatar_m.png";
            } else {
                return "avatar_h.png";
            }
        } else {
            return $foto;
        }
    }
    
    public function getLider() {
    	return $this->getCelula()->getLider();
    }
//    /**
//     * Sobrecarga para asignar un grupo por defecto despues de haber guardado
//     * @param Doctrine_Connection $conn 
//     */
//    public function save(Doctrine_Connection $conn = null) {
//        $grupo = new sfGuardUserGroup();
//        parent::save($conn);
//        $grupo->asignarGrupo($this->getId(), 1);
//    }
    
}