<?php

/**
 * sfGuardUserGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUserGroup extends PluginsfGuardUserGroup {

    /**
     * Asigna un grupo por defecto a un usuario de forma automatica
     * @param type $discipulo_id
     * @param type $grupo_id 
     */
    public function asignarGrupo($discipulo_id, $grupo_id) {
        $grupo = Doctrine_Core::getTable('sfGuardUserGroup')->getGrupoPorIds($discipulo_id, $grupo_id);
        if (count($grupo) <= 0) {
            $this->setUserId($discipulo_id);
            $this->setGroupId($grupo_id);
            $this->save();
        }
    }

}