<?php

/**
 * sfGuardUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class sfGuardUserTable extends PluginsfGuardUserTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object sfGuardUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('sfGuardUser');
    }
    
    /**
     * Obtiene la lista de usuarios que son líderes de célula y de red
     * @return Array Lista de usuarios lideres encontrados
     */
    public static function getLideres() {
        $q = Doctrine::getTable('sfGuardUser')->createQuery('d')->whereIn('d.tipo_discipulo', array(3, 4));
        return $q->execute();
    }

    /**
     * Obtiene la lista de usuarios por tipo
     * @param Integer $tipo El tipo de discipulo
     * @return Array Lista de usuarios encontrados
     */
    public static function getDicipulosPorTipo($tipo) {
        $q = Doctrine::getTable('sfGuardUser')->createQuery('d')->where('d.tipo_discipulo = ?', $tipo);
        return $q->execute();
    }
    
    /**
     * Obtiene el dicipulo que conincide con el ID proporcionado
     * @param type $id_discipulo
     * @return Discipulo El registro encontrado
     */
    public static function getDiscipuloPorId($id_discipulo) {
        $q = Doctrine::getTable('sfGuardUser')->createQuery('d')->where('d.id = ?', $id_discipulo);
        return $q->fetchOne();
    }
    
    /**
     * Obtienen la lista de discípulos en base del género enviado
     * @param integer $idGenero El identificador del género
     * @return Doctrine_Collection
     */
    public function getDiscipulosGenero($idGenero){
    	$q = $this->createQuery('u')
    	->where('u.genero = ?', $idGenero);
    	return $q->execute();
    }
    
}