<?php

/**
 * BasesfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property string $email_address
 * @property timestamp $fecha_nac
 * @property string $est_civil
 * @property string $fotografia
 * @property integer $genero
 * @property integer $tipo_discipulo
 * @property string $codigo_lider_cdfe
 * @property clob $direccion
 * @property string $telefono
 * @property string $movil
 * @property string $sector_ciudad
 * @property string $username
 * @property string $algorithm
 * @property string $salt
 * @property string $password
 * @property boolean $is_active
 * @property boolean $is_super_admin
 * @property timestamp $last_login
 * @property Doctrine_Collection $Groups
 * @property Doctrine_Collection $Permissions
 * @property Asignacion $Asignacion
 * @property Celula $Celula
 * @property MiembroCelula $MiembroCelula
 * @property Doctrine_Collection $sfGuardUserPermission
 * @property Doctrine_Collection $sfGuardUserGroup
 * @property sfGuardRememberKey $RememberKeys
 * @property sfGuardForgotPassword $ForgotPassword
 * @property Doctrine_Collection $Nuevo
 * @property Doctrine_Collection $Discipulo
 * 
 * @method string                getFirstName()             Returns the current record's "first_name" value
 * @method string                getLastName()              Returns the current record's "last_name" value
 * @method string                getEmailAddress()          Returns the current record's "email_address" value
 * @method timestamp             getFechaNac()              Returns the current record's "fecha_nac" value
 * @method string                getEstCivil()              Returns the current record's "est_civil" value
 * @method string                getFotografia()            Returns the current record's "fotografia" value
 * @method integer               getGenero()                Returns the current record's "genero" value
 * @method integer               getTipoDiscipulo()         Returns the current record's "tipo_discipulo" value
 * @method string                getCodigoLiderCdfe()       Returns the current record's "codigo_lider_cdfe" value
 * @method clob                  getDireccion()             Returns the current record's "direccion" value
 * @method string                getTelefono()              Returns the current record's "telefono" value
 * @method string                getMovil()                 Returns the current record's "movil" value
 * @method string                getSectorCiudad()          Returns the current record's "sector_ciudad" value
 * @method string                getUsername()              Returns the current record's "username" value
 * @method string                getAlgorithm()             Returns the current record's "algorithm" value
 * @method string                getSalt()                  Returns the current record's "salt" value
 * @method string                getPassword()              Returns the current record's "password" value
 * @method boolean               getIsActive()              Returns the current record's "is_active" value
 * @method boolean               getIsSuperAdmin()          Returns the current record's "is_super_admin" value
 * @method timestamp             getLastLogin()             Returns the current record's "last_login" value
 * @method Doctrine_Collection   getGroups()                Returns the current record's "Groups" collection
 * @method Doctrine_Collection   getPermissions()           Returns the current record's "Permissions" collection
 * @method Asignacion            getAsignacion()            Returns the current record's "Asignacion" value
 * @method Celula                getCelula()                Returns the current record's "Celula" value
 * @method MiembroCelula         getMiembroCelula()         Returns the current record's "MiembroCelula" value
 * @method Doctrine_Collection   getSfGuardUserPermission() Returns the current record's "sfGuardUserPermission" collection
 * @method Doctrine_Collection   getSfGuardUserGroup()      Returns the current record's "sfGuardUserGroup" collection
 * @method sfGuardRememberKey    getRememberKeys()          Returns the current record's "RememberKeys" value
 * @method sfGuardForgotPassword getForgotPassword()        Returns the current record's "ForgotPassword" value
 * @method Doctrine_Collection   getNuevo()                 Returns the current record's "Nuevo" collection
 * @method Doctrine_Collection   getDiscipulo()             Returns the current record's "Discipulo" collection
 * @method sfGuardUser           setFirstName()             Sets the current record's "first_name" value
 * @method sfGuardUser           setLastName()              Sets the current record's "last_name" value
 * @method sfGuardUser           setEmailAddress()          Sets the current record's "email_address" value
 * @method sfGuardUser           setFechaNac()              Sets the current record's "fecha_nac" value
 * @method sfGuardUser           setEstCivil()              Sets the current record's "est_civil" value
 * @method sfGuardUser           setFotografia()            Sets the current record's "fotografia" value
 * @method sfGuardUser           setGenero()                Sets the current record's "genero" value
 * @method sfGuardUser           setTipoDiscipulo()         Sets the current record's "tipo_discipulo" value
 * @method sfGuardUser           setCodigoLiderCdfe()       Sets the current record's "codigo_lider_cdfe" value
 * @method sfGuardUser           setDireccion()             Sets the current record's "direccion" value
 * @method sfGuardUser           setTelefono()              Sets the current record's "telefono" value
 * @method sfGuardUser           setMovil()                 Sets the current record's "movil" value
 * @method sfGuardUser           setSectorCiudad()          Sets the current record's "sector_ciudad" value
 * @method sfGuardUser           setUsername()              Sets the current record's "username" value
 * @method sfGuardUser           setAlgorithm()             Sets the current record's "algorithm" value
 * @method sfGuardUser           setSalt()                  Sets the current record's "salt" value
 * @method sfGuardUser           setPassword()              Sets the current record's "password" value
 * @method sfGuardUser           setIsActive()              Sets the current record's "is_active" value
 * @method sfGuardUser           setIsSuperAdmin()          Sets the current record's "is_super_admin" value
 * @method sfGuardUser           setLastLogin()             Sets the current record's "last_login" value
 * @method sfGuardUser           setGroups()                Sets the current record's "Groups" collection
 * @method sfGuardUser           setPermissions()           Sets the current record's "Permissions" collection
 * @method sfGuardUser           setAsignacion()            Sets the current record's "Asignacion" value
 * @method sfGuardUser           setCelula()                Sets the current record's "Celula" value
 * @method sfGuardUser           setMiembroCelula()         Sets the current record's "MiembroCelula" value
 * @method sfGuardUser           setSfGuardUserPermission() Sets the current record's "sfGuardUserPermission" collection
 * @method sfGuardUser           setSfGuardUserGroup()      Sets the current record's "sfGuardUserGroup" collection
 * @method sfGuardUser           setRememberKeys()          Sets the current record's "RememberKeys" value
 * @method sfGuardUser           setForgotPassword()        Sets the current record's "ForgotPassword" value
 * @method sfGuardUser           setNuevo()                 Sets the current record's "Nuevo" collection
 * @method sfGuardUser           setDiscipulo()             Sets the current record's "Discipulo" collection
 * 
 * @package    cdfeg12
 * @subpackage model
 * @author     Karina Garcia, Dario Chuquilla
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasesfGuardUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('email_address', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('fecha_nac', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('est_civil', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 15,
             ));
        $this->hasColumn('fotografia', 'string', 255, array(
             'type' => 'string',
             'notnull' => false,
             'default' => '',
             'length' => 255,
             ));
        $this->hasColumn('genero', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('tipo_discipulo', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => 2,
             ));
        $this->hasColumn('codigo_lider_cdfe', 'string', 10, array(
             'type' => 'string',
             'fixed' => 1,
             'notnull' => false,
             'length' => 10,
             ));
        $this->hasColumn('direccion', 'clob', null, array(
             'type' => 'clob',
             'notnull' => true,
             ));
        $this->hasColumn('telefono', 'string', 12, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 12,
             ));
        $this->hasColumn('movil', 'string', 12, array(
             'type' => 'string',
             'fixed' => 1,
             'notnull' => false,
             'length' => 12,
             ));
        $this->hasColumn('sector_ciudad', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('username', 'string', 128, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 128,
             ));
        $this->hasColumn('algorithm', 'string', 128, array(
             'type' => 'string',
             'default' => 'sha1',
             'notnull' => true,
             'length' => 128,
             ));
        $this->hasColumn('salt', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('password', 'string', 128, array(
             'type' => 'string',
             'length' => 128,
             ));
        $this->hasColumn('is_active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('is_super_admin', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             ));


        $this->index('is_active_idx', array(
             'fields' => 
             array(
              0 => 'is_active',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('sfGuardGroup as Groups', array(
             'refClass' => 'sfGuardUserGroup',
             'local' => 'user_id',
             'foreign' => 'group_id'));

        $this->hasMany('sfGuardPermission as Permissions', array(
             'refClass' => 'sfGuardUserPermission',
             'local' => 'user_id',
             'foreign' => 'permission_id'));

        $this->hasOne('Asignacion', array(
             'local' => 'id',
             'foreign' => 'discipulo_lider_id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('Celula', array(
             'local' => 'id',
             'foreign' => 'discipulo_lider_id',
             'onDelete' => 'RESTRICT'));

        $this->hasOne('MiembroCelula', array(
             'local' => 'id',
             'foreign' => 'discipulo_id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('sfGuardUserPermission', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('sfGuardUserGroup', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardRememberKey as RememberKeys', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasOne('sfGuardForgotPassword as ForgotPassword', array(
             'local' => 'id',
             'foreign' => 'user_id'));

        $this->hasMany('Asignacion as Nuevo', array(
             'local' => 'id',
             'foreign' => 'discipulo_nuevo_id'));

        $this->hasMany('Escuela as Discipulo', array(
             'local' => 'id',
             'foreign' => 'discipulo_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}