<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->dropForeignKey('asistencia', 'asistencia_miembro_celula_id_miembro_celula_id');
        $this->createForeignKey('asistencia', 'asistencia_miembro_celula_id_sf_guard_user_id', array(
             'name' => 'asistencia_miembro_celula_id_sf_guard_user_id',
             'local' => 'miembro_celula_id',
             'foreign' => 'id',
             'foreignTable' => 'sf_guard_user',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->addIndex('asistencia', 'asistencia_miembro_celula_id', array(
             'fields' => 
             array(
              0 => 'miembro_celula_id',
             ),
             ));
    }

    public function down()
    {
        $this->createForeignKey('asistencia', 'asistencia_miembro_celula_id_miembro_celula_id', array(
             'name' => 'asistencia_miembro_celula_id_miembro_celula_id',
             'local' => 'miembro_celula_id',
             'foreign' => 'id',
             'foreignTable' => 'miembro_celula',
             'onUpdate' => '',
             'onDelete' => 'RESTRICT',
             ));
        $this->dropForeignKey('asistencia', 'asistencia_miembro_celula_id_sf_guard_user_id');
        $this->removeIndex('asistencia', 'asistencia_miembro_celula_id', array(
             'fields' => 
             array(
              0 => 'miembro_celula_id',
             ),
             ));
    }
}