<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addIndex('reunion', 'Asignacion', array(
             'fields' => 
             array(
              0 => 'fecha',
              1 => 'celula_id',
             ),
             'type' => 'unique',
             ));
    }

    public function down()
    {
        $this->removeIndex('reunion', 'Asignacion', array(
             'fields' => 
             array(
              0 => 'fecha',
              1 => 'celula_id',
             ),
             'type' => 'unique',
             ));
    }
}